version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_install:
      # Install pixi
      - curl -fsSL https://pixi.sh/install.sh | bash
    post_install:
      - $HOME/.pixi/bin/pixi --version
      - $HOME/.pixi/bin/pixi install

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
