name: pystog
channels:
  - conda-forge
dependencies:
  - h5py
  - numpy
  - pytest
  - pytest-cov
  - versioningit
  # packaging
  - anaconda-client
  - boa
  - conda-build
  - conda-verify
  - libmamba
  - libarchive
  - python-build
