name: pystog
channels:
  - conda-forge
dependencies:
  - h5py
  - numpy=1 # for now
  - pre-commit
  - pytest
  - pytest-cov
  - versioningit
  # packaging
  - anaconda-client
  - boa
  - conda-build < 4
  - conda-verify
  - libmamba
  - libarchive
  - python-build
