# load information from pyproject.toml
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
{% set build_number = 0 %}

package:
  name: pystog
  version: {{ version_number }}

source:
  path: ..

build:
  noarch: python
  number: {{ build_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m install . --no-deps --ignore-installed -vvv
  entry_points:
    - pystog_cli = pystog.cli:pystog_cli

requirements:
  host:
    - python
    - versiongit
  build:
    - setuptools
    - versiongit
    - numpy
    - h5py
  run:
    - python
    - numpy
    - h5py

test:
  imports:
    - pystog
    - pystog.stog

about:
  home: {{ url }}
  license: {{ license }}
  license_family: GPL3
  license_file:
  summary: "Transforms reciprocal and real space total scattering functions"

extra:
  recipe-maintainers:
    - Kvieta1990
    - marshallmcdonnell
