{% set data = load_setup_py_data() %}

package:
  name: pystog
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  noarch: python
  string: py{{py}}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pystog_cli = pystog.cli:pystog_cli

requirements:
  build:
    - numpy
    - h5py
  run:
    - numpy
    - h5py

test:
  imports:
    - pystog
    - pystog.stog

about:
  home: https://github.com/neutrons/pystog
  license: GPL (version 3)
  license_family: GPL3
  license_file:
  summary: "Transforms reciprocal and real space total scattering functions"

extra:
  recipe-maintainers:
    - Kvieta1990
    - marshallmcdonnell
