name: pystog

env:
  PYTHON_MAIN_VERSION: 3.11

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
    tags: ['v*']

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults

      - name: Conda install deps
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml

      - name: build conda package
        run: |
          # set up environment
          conda init bash
          source ~/.bashrc
          conda activate pystog
          cd conda.recipe
          echo "versioningit $(versioningit ../)"
          # build the package
          VERSION=$(versioningit ../) conda mambabuild --output-folder . .
          conda verify noarch/pystog*.tar.bz2
      - name: upload conda package to anaconda
        shell: bash -l {0}
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is main or rc depending on the tag-name
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          conda install anaconda-client
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          anaconda upload --label $CONDA_LABEL conda.recipe/noarch/pystog*.tar.bz2
