name: test

env:
  PYTHON_MAIN_VERSION: 3.11

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
    tags: ['v*']

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults

      - name: Conda install deps
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml

      - name: run tests
        run: |
          echo "running tests"
          conda init bash
          source ~/.bashrc
          conda activate pystog
          python -m pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: build conda package
        run: |
          # test that the conda package builds
          conda init bash
          source ~/.bashrc
          conda activate pystog
          cd conda.recipe
          echo "versioningit $(versioningit ../)"
          # conda channels could have been defined in the conda-incubator, but you can copy/paste the lines
          # below to build the conda package in your local machine
          VERSION=$(versioningit ../) conda mambabuild --output-folder . .
          conda verify noarch/pystog*.tar.bz2
